### ISSUE TITLE
Schema support incomplete?

### ISSUE THREAD

**Issue by ergo70** [citusdata/pg_shard#127] opened 2015-07-22 11:21 UTC
Having a table in a schema other than public seems to be working at first:

```sql
CREATE TABLE test.t1
(
  id integer NOT NULL,
  value integer,
  CONSTRAINT pk_t1 PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);

SELECT master_create_distributed_table('test.t1', 'id');
SELECT master_create_worker_shards('test.t1', 16, 2);
```

(The schema has to exist on the worker nodes though, it is not created)

But:

```sql
insert into test.t1 values (0,0)

# WARNING:  Bad result from localhost:5434
# DETAIL:  Remote message: relation "t1_10066" does not exist
# WARNING:  Bad result from localhost:5433
# DETAIL:  Remote message: relation "t1_10066" does not exist
# ERROR:  could not modify any active placements
# ********** Error **********
# ERROR: could not modify any active placements
# SQL state: XX000
```

Shouldn't that be `test.t1_10066` in order to work?

**Comment by jasonmp85** [comment] 2015-07-27 20:06
Hey @ergo70: I'm closing this as a duplicate of #15.

Thanks for the report: It appears you found precisely the same problem documented in the earlier issue.

Can you add a small comment to #15 explaining your use case or need for this feature? It'll serve as a reminder that we had an external user actually hit this bug.

Thanks!

**Closed by jasonmp85** 2015-07-27 20:06 UTC
Labels: invalid
